{% set name = "parse" %}
{% set version = "1.20.2" %}
{% set sha256 = "b41d604d16503c79d81af5165155c0b20f6c8d6c559efa66b4b695c3e5a0a0ce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - parse

about:
  home: https://github.com/r1chardj0n3s/parse
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: parse() is the opposite of format()
  description: |
    Parse strings using a specification based on the Python format() syntax.
  doc_url: https://github.com/r1chardj0n3s/parse/blob/master/README.rst
  dev_url: https://github.com/r1chardj0n3s/parse

extra:
  recipe-maintainers:
    - stuertz
